/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpracticas;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique Rodríguez
 */
public class frmPractica1 extends javax.swing.JFrame {
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Texto","pdf","doc", "docx","odt","xls","xlsx");
    private JFileChooser buscador = new JFileChooser();
    int flaLo = 0;
    Conexion z = new Conexion();
    DefaultTableModel mAutores = new DefaultTableModel();
    private int action = 1;
    private int contador = 0;
    int nurmeroFilas = 0;
    /**
     * Creates new form frmPractica
     */
    public frmPractica1() {
        initComponents();
        circunscripciones();
        metodologia();
        confGrilla();
//        if(Integer.parseInt(txtId.getText().toString()) == FrmArea.band){
//            cargaGilla();
//        }
        rol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabContenedor = new javax.swing.JTabbedPane();
        pnlIdentidad = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        lblTituo = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFin = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();
        txtTema = new javax.swing.JTextField();
        lblLocalidad = new javax.swing.JLabel();
        cboLocalidad = new javax.swing.JComboBox();
        lblLocalidad1 = new javax.swing.JLabel();
        cboCircunscripciones = new javax.swing.JComboBox();
        lblTituo1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cboInicio = new org.freixas.jcalendar.JCalendarCombo();
        cboFin = new org.freixas.jcalendar.JCalendarCombo();
        pnlDesarrollo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblMetodologia = new javax.swing.JLabel();
        cboMetodologia = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableAutores = new javax.swing.JTable();
        btnBorrarAutor = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAId = new javax.swing.JTextField();
        txtANombre = new javax.swing.JTextField();
        txtAApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAutorTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAutorEmail = new javax.swing.JTextField();
        cborol = new javax.swing.JComboBox();
        btnAAdd = new javax.swing.JButton();
        btnXAutor = new javax.swing.JButton();
        pnlConclusion = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtConclusion = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAcuerdos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnAddFile = new javax.swing.JButton();
        pnlAcciones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlIdentidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificación de la práctica"));

        txtTitulo.setToolTipText("Escriba el título que se le dío a la Actividad");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lblTituo.setText("Título");

        lblInicio.setText("Fecha de Inicio");

        lblFin.setText("Fecha de fin");

        lblTema.setText("Tema");

        txtTema.setToolTipText("Escriba el Tema, ejemplo Acceso a la Información de personas con discapacidad");

        lblLocalidad.setText("Localidad");

        cboLocalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLocalidad1.setText("Circunscripción");

        cboCircunscripciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCircunscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCircunscripcionesActionPerformed(evt);
            }
        });

        lblTituo1.setText("ID");

        txtId.setToolTipText("Escriba el título que se le dío a la Actividad");
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIdentidadLayout = new javax.swing.GroupLayout(pnlIdentidad);
        pnlIdentidad.setLayout(pnlIdentidadLayout);
        pnlIdentidadLayout.setHorizontalGroup(
            pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIdentidadLayout.createSequentialGroup()
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblInicio)
                        .addComponent(lblTituo)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTema)
                            .addComponent(lblLocalidad)
                            .addComponent(lblLocalidad1))
                        .addComponent(lblTituo1))
                    .addComponent(lblFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIdentidadLayout.createSequentialGroup()
                        .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTema, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(cboLocalidad, 0, 186, Short.MAX_VALUE)
                                .addComponent(cboCircunscripciones, 0, 186, Short.MAX_VALUE))
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addGap(494, 494, 494))
                    .addGroup(pnlIdentidadLayout.createSequentialGroup()
                        .addComponent(cboInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlIdentidadLayout.createSequentialGroup()
                        .addComponent(cboFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlIdentidadLayout.setVerticalGroup(
            pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentidadLayout.createSequentialGroup()
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIdentidadLayout.createSequentialGroup()
                        .addComponent(lblInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(lblFin))
                    .addGroup(pnlIdentidadLayout.createSequentialGroup()
                        .addComponent(cboInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidad1)
                    .addComponent(cboCircunscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidad)
                    .addComponent(cboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIdentidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(311, 311, 311))
        );

        tabContenedor.addTab("Identificación", pnlIdentidad);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Breve descripción de la actividad"));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        lblMetodologia.setText("Metodología");

        cboMetodologia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Autores"));

        tableAutores.setModel(mAutores);
        tableAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAutoresMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableAutores);

        btnBorrarAutor.setText("Borrar");
        btnBorrarAutor.setEnabled(false);
        btnBorrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAutorActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("id");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        txtAId.setEnabled(false);
        txtAId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAIdActionPerformed(evt);
            }
        });

        txtANombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANombreActionPerformed(evt);
            }
        });
        txtANombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtANombreKeyReleased(evt);
            }
        });

        txtAApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAApellidoActionPerformed(evt);
            }
        });
        txtAApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAApellidoKeyReleased(evt);
            }
        });

        jLabel5.setText("Email");

        txtAutorTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorTelefonoActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefono");

        txtAutorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorEmailActionPerformed(evt);
            }
        });

        cborol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cborol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cborolActionPerformed(evt);
            }
        });

        btnAAdd.setText("Add");
        btnAAdd.setEnabled(false);
        btnAAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAAddActionPerformed(evt);
            }
        });

        btnXAutor.setText("xxxx");
        btnXAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtAId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addComponent(txtAApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cborol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnBorrarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(btnXAutor)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cborol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAAdd))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtANombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAutorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(txtAutorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnBorrarAutor)
                    .addComponent(jButton4)
                    .addComponent(btnXAutor))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDesarrolloLayout = new javax.swing.GroupLayout(pnlDesarrollo);
        pnlDesarrollo.setLayout(pnlDesarrolloLayout);
        pnlDesarrolloLayout.setHorizontalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                        .addComponent(lblMetodologia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDesarrolloLayout.setVerticalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesarrolloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodologia)
                    .addComponent(cboMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tabContenedor.addTab("Desarrollo", pnlDesarrollo);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Conclusión"));

        txtConclusion.setColumns(20);
        txtConclusion.setRows(5);
        jScrollPane5.setViewportView(txtConclusion);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Acuerdos tomados"));

        txtAcuerdos.setColumns(20);
        txtAcuerdos.setRows(5);
        jScrollPane6.setViewportView(txtAcuerdos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        jLabel4.setText("Documentos Generados");

        txtDoc.setEnabled(false);

        jButton5.setText("Examinar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnAddFile.setText("Add");
        btnAddFile.setEnabled(false);
        btnAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConclusionLayout = new javax.swing.GroupLayout(pnlConclusion);
        pnlConclusion.setLayout(pnlConclusionLayout);
        pnlConclusionLayout.setHorizontalGroup(
            pnlConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConclusionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pnlConclusionLayout.createSequentialGroup()
                        .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFile))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlConclusionLayout.setVerticalGroup(
            pnlConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConclusionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(btnAddFile))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tabContenedor.addTab("Conclusión", pnlConclusion);

        pnlAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnAgregar.setText("Agregar");

        btnModificar.setText("Modificar");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");

        btnCancelar.setText("Cancelar");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpiarGrilla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtAIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAIdActionPerformed

    private void txtANombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANombreActionPerformed

    private void txtAApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAApellidoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int result = buscador.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION){
               File file = buscador.getSelectedFile();
               txtDoc.setText(String.valueOf(file));
               btnAddFile.setEnabled(true);
         }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mostrarPaneles(boolean si){
        pnlDesarrollo.setVisible(si);
        pnlConclusion.setVisible(si);
    }
    
    private void agregar(){
        fotoclass f = new fotoclass();        
        f.guardarfoto("archivo", txtDoc.getText().toString());
    }
    
    private void cboCircunscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCircunscripcionesActionPerformed
        flaLo = 1;
        localidad();
    }//GEN-LAST:event_cboCircunscripcionesActionPerformed

    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        agregar();
    }//GEN-LAST:event_btnAddFileActionPerformed

    private void btnAAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAAddActionPerformed
//        cargaGilla();
        txtAApellido.setText(null);
        txtAId.setText(null);
        txtANombre.setText(null);
        txtAutorEmail.setText(null);
        txtAutorTelefono.setText(null);
        
    }//GEN-LAST:event_btnAAddActionPerformed

    private void txtAutorTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorTelefonoActionPerformed

    private void cborolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cborolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cborolActionPerformed

    private void txtAutorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorEmailActionPerformed

    private void txtANombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANombreKeyReleased
        activarAdd();
    }//GEN-LAST:event_txtANombreKeyReleased

    private void txtAApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAApellidoKeyReleased
        activarAdd();
    }//GEN-LAST:event_txtAApellidoKeyReleased

    private void tableAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAutoresMouseClicked
        btnBorrarAutor.setEnabled(true);
    }//GEN-LAST:event_tableAutoresMouseClicked

    private void btnBorrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAutorActionPerformed
        borrarFila();
        btnBorrarAutor.setEnabled(false);
    }//GEN-LAST:event_btnBorrarAutorActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        abm(action);
        action = 2;
        nurmeroFilas = tableAutores.getRowCount();
        if(nurmeroFilas > 0)
            contador = 1;
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnXAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXAutorActionPerformed
        int xa = Integer.parseInt(txtId.getText().toString());
        FrmArea autor = new FrmArea(this, true, xa);
        autor.setVisible(true);
    }//GEN-LAST:event_btnXAutorActionPerformed

    private void borrarFila(){
        int fila = tableAutores.getSelectedRow();
        mAutores.removeRow(fila);
    }
    
    private void abm(int accion){
        try {
            int id = 1;
            String fechIni = z.dateFormat(cboInicio.getDate()).toString();
            String fechFin = z.dateFormat(cboFin.getDate()).toString();
            int meto = z.buscaCod("SELECT id FROM metodologias where descripcion like '%"+cboMetodologia.getSelectedItem().toString()+"%'");
            int loca = z.buscaCod("SELECT * FROM localidades where nombre like '%"+cboLocalidad.getSelectedItem().toString()+"%'");
            if(accion == 2){
                id = Integer.parseInt(txtId.getText().toString());
            }
            String sql = "CALL rpractica ("+accion+", "+id+", '"+txtTitulo.getText().toString()+"', '"+
                    fechIni+"', '"+fechFin+"', '"+txtTema.getText().toString()+"', '"+meto+"', '"+txtDescripcion.getText().toString()+"', '"+
                    txtConclusion.getText().toString()+"', '"+txtAcuerdos.getText().toString()+"', "+loca+")";
            System.out.println(sql);
            z.snt = z.con.createStatement();
            z.snt.executeUpdate(sql);
            z.rs = z.snt.executeQuery("select max(id) as id from practicas limit 1;");
            z.rs.next();
            txtId.setText(z.rs.getString("id"));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    
    private void circunscripciones(){
        try {
            String sql = "SELECT * FROM circunscripciones order by descripcion ";
                    z.snt = z.con.createStatement();
                    z.rs = z.snt.executeQuery(sql);
                    cboCircunscripciones.removeAllItems();
                    while (z.rs.next()) {
                        cboCircunscripciones.addItem(z.rs.getString("descripcion"));
        }
        } catch (SQLException ex) {
            Logger.getLogger(frmPractica1.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
    
    private void rol(){
        try {
            String sql = "SELECT * FROM roles where id > 3 order by nombre";
                    z.snt = z.con.createStatement();
                    z.rs = z.snt.executeQuery(sql);
                    cborol.removeAllItems();
                    while (z.rs.next()) {
                        cborol.addItem(z.rs.getString("nombre"));
        }
        } catch (SQLException ex) {
            Logger.getLogger(frmPractica1.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
    
    private void activarAdd(){
        if(!txtANombre.getText().equals("") && !txtAApellido.getText().equals("")){
            btnAAdd.setEnabled(true);
        }
    }
    
    private void localidad(){
        String buscar;
        buscar = "SELECT * FROM circunscripciones where descripcion like '%"+cboCircunscripciones.getSelectedItem()+"%'";
        
        System.out.print(buscar);        
        try {
            Conexion z = new Conexion();
            String sql = "SELECT * FROM localidades where circunscripciones = "+z.buscaCod(buscar) +" order by nombre ";
                    z.snt = z.con.createStatement();
                    z.rs = z.snt.executeQuery(sql);
                    cboLocalidad.removeAllItems();
                    while (z.rs.next()) {
                        cboLocalidad.addItem(z.rs.getString("nombre"));
        }
        } catch (SQLException ex) {
            Logger.getLogger(frmPractica1.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
    
    private void metodologia(){
        try {
            Conexion z = new Conexion();
            String sql = "SELECT * FROM metodologias";
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            cboMetodologia.removeAllItems();
            while (z.rs.next()) {
                cboMetodologia.addItem(z.rs.getString("descripcion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPractica1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   private void confGrilla(){
       mAutores.addColumn("id");
       mAutores.addColumn("Nombre");
       mAutores.addColumn("Apellido");
       mAutores.addColumn("Teléfono");
       mAutores.addColumn("Email");
       mAutores.addColumn("Rol");
   }
    
//    private void cargaGilla(){
//        try {
//            String[] datos = new String[6];
//            String sql = "SELECT id, nombre, apellido, email, telefono, roles FROM bpracticas.vautores where practica_id = "+txtId.getText().toString();
//            z.snt = z.con.createStatement();
//            z.rs = z.snt.executeQuery(sql);
//            while(z.rs.next()){
//                datos[0] = txtANombre.getText().toString();
//                datos[1] = txtAApellido.getText().toString();
//                datos[2] = txtAutorTelefono.getText().toString();
//                datos[3] = txtAutorEmail.getText().toString();
//                datos[4] = cborol.getSelectedItem().toString();
//                datos[5] = cborol.getSelectedItem().toString();
//                mAutores.addRow(datos);
//            }
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//        }
//          
//    }
    
    private void limpiarGrilla() {   
         while (mAutores.getRowCount() > 0)
             mAutores.removeRow(0);
     }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(
                        UIManager.getSystemLookAndFeelClassName());
                    new frmPractica1().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                } catch (InstantiationException ex) {
                    ex.printStackTrace();
                } catch (IllegalAccessException ex) {
                    ex.printStackTrace();
                } catch (UnsupportedLookAndFeelException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAAdd;
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarAutor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnXAutor;
    private javax.swing.JComboBox cboCircunscripciones;
    private org.freixas.jcalendar.JCalendarCombo cboFin;
    private org.freixas.jcalendar.JCalendarCombo cboInicio;
    private javax.swing.JComboBox cboLocalidad;
    private javax.swing.JComboBox cboMetodologia;
    private javax.swing.JComboBox cborol;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblLocalidad1;
    private javax.swing.JLabel lblMetodologia;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel lblTituo;
    private javax.swing.JLabel lblTituo1;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlConclusion;
    private javax.swing.JPanel pnlDesarrollo;
    private javax.swing.JPanel pnlIdentidad;
    private javax.swing.JTabbedPane tabContenedor;
    private javax.swing.JTable tableAutores;
    private javax.swing.JTextField txtAApellido;
    private javax.swing.JTextField txtAId;
    private javax.swing.JTextField txtANombre;
    private javax.swing.JTextArea txtAcuerdos;
    private javax.swing.JTextField txtAutorEmail;
    private javax.swing.JTextField txtAutorTelefono;
    private javax.swing.JTextArea txtConclusion;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
