/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bpracticas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique Rodríguez CEJ
 * @version 0.1
 */

public class FrmPrincipal extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    Conexion z = new Conexion();
    static private int modificaras = 0;
    static private String local;
    static private String circuns;
    static private int evaluar =0;
    static private int estEva =0;

    public static int getEstEva() {
        return estEva;
    }

    public static void setEstEva(int estEva) {
        FrmPrincipal.estEva = estEva;
    }
    
    public static int getEvaluar() {
        return evaluar;
    }

    public static void setEvaluar(int evaluar) {
        FrmPrincipal.evaluar = evaluar;
    }

    public static String getCircuns() {
        return circuns;
    }

    public static void setCircuns(String circuns) {
        FrmPrincipal.circuns = circuns;
    }

    public static String getLocal() {
        return local;
    }

    public static void setLocal(String local) {
        FrmPrincipal.local = local;
    }

    public static int getModificaras() {
        return modificaras;
    }

    public static void setModificaras(int modificaras) {
        FrmPrincipal.modificaras = modificaras;
    }
    
    private void setRolPermiso(){
        switch (FrmAcceso.getRol()){
            case 2 : menHerramientas.setVisible(false);
                break;
            case 3 : menHerramientas.setVisible(false);
                    menEva.setVisible(false);
                break;
        }
    }
    
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        confiGrilla();
        cargaGrilla();
        setRolPermiso();
            
    }

    private void borrarPractica(){
        String sql = "UPDATE practicas SET disponible=0 WHERE id="+modelo.getValueAt(tabla.getSelectedRow(), 0);
        int aux = JOptionPane.showConfirmDialog(null, "¿Realmente desea borrar la practica borrar?");
        if(aux == JOptionPane.YES_OPTION){
            try {
                z.snt = z.con.createStatement();
                z.snt.executeUpdate(sql);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            cargaGrilla();
        }else{
            
        }
        
    }
    
    private void confiGrilla(){
        modelo.addColumn("id");
        modelo.addColumn("Titulo");
        modelo.addColumn("Inicio");
        modelo.addColumn("Fin");
        modelo.addColumn("localidad");
        modelo.addColumn("cirunscripcion");
    }
    
    private void cargaGrilla(){
        try {
            
            String sql = "SELECT id, titulo, inicio, fin, localidades, circunscripciones FROM vpractica where disponible = 1";
            if(txtFiltro.getText().length() > 0 && !chkFiltro.isSelected())
                sql = sql+" and titulo like '%"+txtFiltro.getText().toString()+"%'";
            if (chkFiltro.isSelected() && txtFiltro.getText().length() <= 0){
                sql = sql+" and inicio BETWEEN '"+z.dateFormat(cboDesde.getDate()) +"' AND '"+z.dateFormat(cboHasta.getDate()) +"'";
            }
            if(txtFiltro.getText().length() > 0 && chkFiltro.isSelected()){
                sql = sql+" and titulo like '%"+txtFiltro.getText().toString()+"%' and inicio BETWEEN '"+z.dateFormat(cboDesde.getDate()) +"' AND '"+z.dateFormat(cboHasta.getDate()) +"'";
            }
            
            modelo.setRowCount(0);
            String[] datos = new String[6];
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            while(z.rs.next()){
                datos[0] = z.rs.getString(1);
                datos[1] = z.rs.getString(2);
                datos[2] = z.rs.getString(3);
                datos[3] = z.rs.getString(4);
                datos[4] = z.rs.getString(5);
                datos[5] = z.rs.getString(6);
                modelo.addRow(datos);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    
    private void evaluar(){
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        mBorrar = new javax.swing.JMenuItem();
        mModificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboDesde = new org.freixas.jcalendar.JCalendarCombo();
        cboHasta = new org.freixas.jcalendar.JCalendarCombo();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkFiltro = new javax.swing.JCheckBox();
        pnlAcciones = new javax.swing.JPanel();
        lblAdd = new javax.swing.JLabel();
        lblBorrar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        lblRefrescar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menHerramientas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menUsuario = new javax.swing.JMenuItem();
        menEva = new javax.swing.JMenu();
        menEvaInnovación = new javax.swing.JMenuItem();
        menEvaParticipacion = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        mBorrar.setText("Borrar");
        mBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBorrarActionPerformed(evt);
            }
        });
        popMenu.add(mBorrar);

        mModificar.setText("Modificar");
        mModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificarActionPerformed(evt);
            }
        });
        popMenu.add(mModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco de buenas prácticas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Practicas"));

        tabla.setModel(modelo);
        tabla.setToolTipText("Haba doble clic para editar una practica");
        tabla.setComponentPopupMenu(popMenu);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Desde");

        cboDesde.setEnabled(false);

        cboHasta.setEnabled(false);

        jLabel2.setText("Filtrar");

        jLabel3.setText("Hasta");

        chkFiltro.setText("Activar filtro de fecha");
        chkFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFiltroActionPerformed(evt);
            }
        });

        pnlAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        lblAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        lblAdd.setText("Añadir");
        lblAdd.setToolTipText("Agregar Practica");
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
        });

        lblBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove.png"))); // NOI18N
        lblBorrar.setText("Borrar");
        lblBorrar.setToolTipText("Borrar");
        lblBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBorrarMouseClicked(evt);
            }
        });

        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rename Document.png"))); // NOI18N
        lblModificar.setText("Modificar");
        lblModificar.setToolTipText("Modificar");
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });

        lblRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View-refresh.png"))); // NOI18N
        lblRefrescar.setText("Refrescar");
        lblRefrescar.setToolTipText("Refrescar");
        lblRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefrescarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(lblAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(lblBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(lblModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(lblRefrescar)
                .addContainerGap())
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBorrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRefrescar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nueva Practica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menSalir.setText("Salir");
        menSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem3.setText("Modificar");
        jMenu2.add(jMenuItem3);

        jMenuItem5.setText("borrar");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        menHerramientas.setText("Herramientas");
        menHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menHerramientasActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("circunscripciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menHerramientas.add(jMenuItem1);

        menUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menUsuario.setText("Usuarios");
        menUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menUsuarioActionPerformed(evt);
            }
        });
        menHerramientas.add(menUsuario);

        jMenuBar1.add(menHerramientas);

        menEva.setText("Evaluar");

        menEvaInnovación.setText("Innovacion");
        menEvaInnovación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEvaInnovaciónActionPerformed(evt);
            }
        });
        menEva.add(menEvaInnovación);

        menEvaParticipacion.setText("Participación");
        menEvaParticipacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEvaParticipacionActionPerformed(evt);
            }
        });
        menEva.add(menEvaParticipacion);

        jMenuItem4.setText("Replicabilidad");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menEva.add(jMenuItem4);

        jMenuBar1.add(menEva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkFiltro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(cboDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFiltro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menHerramientasActionPerformed
        
    }//GEN-LAST:event_menHerramientasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmCircunscripcion circunscripciones = new FrmCircunscripcion();
        circunscripciones.setVisible(true);
        circunscripciones.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmPractica practica = new FrmPractica();
        practica.setVisible(true);
        practica.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void chkFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFiltroActionPerformed
        if(chkFiltro.isSelected()){
            cboDesde.setEnabled(true);
            cboHasta.setEnabled(true);
        }else{
            cboDesde.setEnabled(false);
            cboHasta.setEnabled(false);
        }
    }//GEN-LAST:event_chkFiltroActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
//        menEvaluar.setEnabled(true);
//        if (evt.getClickCount()==2){
//            FrmPractica pra = new FrmPractica();
//            pra.setVisible(true);
//            pra.setLocationRelativeTo(null);
//        }
            
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargaGrilla();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        cargaGrilla();
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void menUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menUsuarioActionPerformed
        FrmUsuario usuario = new FrmUsuario();
        usuario.setLocationRelativeTo(null);
        usuario.setVisible(true);
    }//GEN-LAST:event_menUsuarioActionPerformed

    private void mBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBorrarActionPerformed
        borrarPractica();
    }//GEN-LAST:event_mBorrarActionPerformed

    private void menSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_menSalirActionPerformed

    private void mModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificarActionPerformed
        setModificaras(Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 0).toString()));
        FrmPractica practica = new FrmPractica();
        practica.setLocationRelativeTo(null);
        practica.setVisible(true);
    }//GEN-LAST:event_mModificarActionPerformed

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked
        FrmPractica practica = new FrmPractica();
        practica.setLocationRelativeTo(null);
        practica.setVisible(true);
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefrescarMouseClicked
        cargaGrilla();
    }//GEN-LAST:event_lblRefrescarMouseClicked

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
        if(tabla.getSelectedRow() > -1){
            setModificaras(Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 0).toString()));
            FrmPractica practica = new FrmPractica();
            practica.setLocationRelativeTo(null);
            practica.setVisible(true);
        }
        
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBorrarMouseClicked
        if(tabla.getSelectedRow() > -1){
            borrarPractica();
        }
    }//GEN-LAST:event_lblBorrarMouseClicked

    private void menEvaInnovaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEvaInnovaciónActionPerformed
//        if (criterio("innovacion") == 0) {
            setEvaluar(Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 0).toString()));
            FrmInnovacion innovacion = new FrmInnovacion();
            innovacion.setVisible(true);
            innovacion.setLocationRelativeTo(null);
  //      }else{
            int a = JOptionPane.showConfirmDialog(this, "Esta práctica ya fue evaluada, desea modifcarla?");
            if(a == JOptionPane.OK_OPTION){
                
    //        }
        }
        
    }//GEN-LAST:event_menEvaInnovaciónActionPerformed

    private int saberEvaluar(String factor){
        int var = 0;
        try {
            
            
            String sql= "SELECT "+factor+" FROM practicas where id ="+modelo.getValueAt(tabla.getSelectedRow(), 0).toString();
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            z.rs.next();
            var = Integer.parseInt(z.rs.getString(factor));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return var;
    }
    
    
    private void menEvaParticipacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEvaParticipacionActionPerformed
        setEvaluar(Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 0).toString()));
        FrmParticipacion participacion = new FrmParticipacion();
        participacion.setVisible(true);
        participacion.setLocationRelativeTo(null);
    }//GEN-LAST:event_menEvaParticipacionActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(saberEvaluar("replicabilidad") == 0){
            setEvaluar(Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 0).toString()));
            FrmReplicabilidad replicabilidad = new FrmReplicabilidad();
            replicabilidad.setVisible(true);
            replicabilidad.setLocationRelativeTo(null);
        }else{
            int op = JOptionPane.showConfirmDialog(null,"El criterio para esta práctica ya fue evaluado con anterioridad, desea modificar la evalucaicón","Seleccione una opción",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
            if(op == JOptionPane.OK_OPTION){
                setEvaluar(Integer.parseInt(modelo.getValueAt(tabla.getSelectedRow(), 0).toString()));
                FrmReplicabilidad replicabilidad = new FrmReplicabilidad();
                replicabilidad.setVisible(true);
                replicabilidad.setLocationRelativeTo(null);
                setEstEva(1);
            }
        }
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    
    private int criterio(String criterio){
         int valCriterio =0;
        try {
            String sql = "SELECT "+criterio+" FROM practicas where id ="+modelo.getValueAt(tabla.getSelectedRow(), 0).toString();
            z.snt = z.con.createStatement();
            z.rs = z.snt.executeQuery(sql);
            z.rs.next();
            valCriterio = Integer.parseInt(z.rs.getString(1));

        } catch (SQLException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        return valCriterio;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo cboDesde;
    private org.freixas.jcalendar.JCalendarCombo cboHasta;
    private javax.swing.JCheckBox chkFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblRefrescar;
    private javax.swing.JMenuItem mBorrar;
    private javax.swing.JMenuItem mModificar;
    private javax.swing.JMenu menEva;
    private javax.swing.JMenuItem menEvaInnovación;
    private javax.swing.JMenuItem menEvaParticipacion;
    private javax.swing.JMenu menHerramientas;
    private javax.swing.JMenuItem menSalir;
    private javax.swing.JMenuItem menUsuario;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
